### PR TITLE
changes the colour of the growl notifications. The tick is still the …

### PR DESCRIPTION
**Pull request by fredkingham**
…wrong colour, but this is not incredibly noticalbe.. its an improvement

### CODE REVIEW

**Comment by davidmiller** [comment]
@fredkingham Do you still want this colour update? If so can we re-point at the new relevant branch and re-open with screenshots?

**Comment by fredkingham** [comment]
👍

**Comment by fredkingham** [comment]
screen shot 2018-09-27 at 16 20 45

**Comment by fredkingham** [comment]
Notably the tick is still wrong colour but that's a bit extensive to change 😞  I think this is enough, the tick is quite subtle

**Comment by fredkingham** [comment]
repointing

**Pull request closed without merging**
