### PR TITLE
Growl alert background color

### PR DESCRIPTION
**Pull request by fredkingham**

### CODE REVIEW

**Comment by fredkingham** [comment]
screen shot 2018-09-27 at 16 20 45

**Comment by davidmiller** [comment]
I think this needs merge conflicts resolving now...
If we're going to do it, can we not find a css class for the tick and make it white?

**Comment by fredkingham** [comment]
@davidmiller its not a css class its an image 😞 I can try to colour it but it'll be awkward...

**Comment by fredkingham** [comment]
The previous behaviour is preferred.

**Comment by davidmiller** [comment]
screen shot 2018-10-02 at 15 58 44
Honestly, I prefer the green on green to green on blue if we can't easily change the image....

**Pull request closed without merging**
