### PR TITLE
adds in a communication/nationality/citizenship pathway and panel

### LINKED ISSUE #569: Merge Communication with Nationality and Citizenship
It should be the form that we see in the initial assessment.

look at the branch LTBI-clinic

### PR DESCRIPTION
**Pull request by fredkingham**
fixes #569

### CODE REVIEW

**Comment by fredkingham** [comment]
screen shot 2018-11-22 at 11 28 15
screen shot 2018-11-22 at 11 28 09

**Comment by fredkingham** [comment]
I've gone for a similar layout to our Social History form and our Location form. We should look at formalising our display panel layouts as they differ a lot.

**Comment by davidmiller** [comment]
I think we probably want the same merged step in the TB initial assessment form ?

**Comment by fredkingham** [comment]
@davidmiller 👍

**Pull request merged**
