### PR TITLE
Removes useless comment tags

### PR DESCRIPTION
**Pull request by fredkingham**
These comment tags don't work so we may as well remove them.

Django supports 
```{# one line comment #}```

or 
```
{% comment %}
this is commented
{% endcomment %}
```
{# comment #} something {# endcomment #} is not a thing and probably just confuses things 

https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#templatetag

### CODE REVIEW

**Comment by davidmiller** [comment]
Is there a related ticket to remove that permission ?

**Comment by fredkingham** [comment]
There can be, I'm not sure that blocks this.

**Comment by fredkingham** [comment]
Remove the if clause in the template instead

**Comment by davidmiller** [comment]
Is this the right branch?

**Pull request merged**
